---

- name: Add passwordless connection for jenkins
  copy: src=authorized_keys dest=/home/jenkins/.ssh/authorized_keys mode=0600 owner=jenkins

- name: Install CouchDB
  yum: name={{item}} state=present
  with_items:
   - couchdb

- name: Start CouchDB
  service: name=couchdb state=started

#Ensure Jenkins is NOT installed: the master auto-installs it!
- name: Ensure Jenkins is NOT installed
  yum: name=jenkins state=absent

# Create Jenkins work directory
- name: Create /var/jenkins
  file: path=/var/jenkins state=directory mode=0700 owner=jenkins

